name: "dask_terminate"
description: Terminate a Dask cluster by writing a marker file to the work dir
keywords:
  - dask
tools:
  - spark:
      description: Apache Spark is an analytics engine for large-scale data processing
      homepage: https://spark.apache.org/
      documentation: https://spark.apache.org/docs/latest/
      tool_dev_url: https://github.com/apache/spark
      licence: ["Apache License 2.0"]

input:
  - meta:
      type: map

  - cluster_work_dir:
      type: path
      description: |
        The cluster work directory.

output:
  - meta:
      type: map

  - cluster_work_fullpath:
      type: string
      description: |
        Full path to the cluster work directory.

authors:
  - "@cgoina"
  - "@krokicki"
