name: dask_startworker
description: Start a dask worker
keywords:
  - dask
tools:
  - dask:
      description: Dask is a flexible library for parallel computing in Python.
      homepage: https://www.dask.org/
      documentation: https://docs.dask.org/en/stable/
      tool_dev_url: https://github.com/dask/dask
      licence: ["BSD 3-Clause License"]

input:
  - meta:
      type: map
  - scheduler_address:
      type: string
      description: |
        Scheduler's IP address
  - cluster_work_dir:
      type: path
      description: |
        The cluster work directory where the scheduler will run
  - worker_id:
      type: string
      description: |
        Worker's ID
  - data:
      type: path
      description: |
        Shared path (or list of paths) which should be mounted in the worker for access
  - worker_cores:
      type: int
      description: Number of cores per worker
  - worker_mem_in_gb:
      type: int
      description: Memory in GB to be allocated to each worker

output:
  - meta:
      type: map
  - cluster_work_fullpath:
      type: string
      description: |
        Full path to the cluster work directory where the scheduler is running
  - worker_name:
      type: string
      description: |
        Dask worker name
  - worker_dir:
      type: string
      description: |
        Dask worker dir
  - versions:
      type: string
      description: |
        Software versions file

authors:
  - "@cgoina"
  - "@krokicki"
